println(List())
println(Nil)
println(List("Cool", "tools", "rule"))
val thrill = "Will" :: "fill" :: "until" :: Nil
println(thrill)
println(List("a", "b") ::: List("c", "d"))
println(thrill(2))
println(thrill.count(s => s.length == 4))
println(thrill.drop(2))
println(thrill.dropRight(2))
println(thrill.exists(s => s== "until"))
println(thrill.filter(s => s.length == 4))
println(thrill.forall(s => s.endsWith("l")))
println(thrill.foreach(s => print(s)))
println(thrill.foreach(print))
println(thrill.head)
println(thrill.init)
println(thrill.isEmpty)
println(thrill.last)
println(thrill.length)
println(thrill.map(s => s + "y"))
println(thrill.mkString(", "))
// remove is not a member of List
println(thrill.filterNot(s => s.length == 4))
println(thrill.reverse)
// sort is not a member of List
println(thrill.sortWith((s, t) => s.charAt(0).toLower < t.charAt(0).toLower))
println(thrill.tail)
