val pair = (99, "Luftbaloons")
println(pair._1)
println(pair._2)

val tuple = ('u', 'r', "the", 1, 4, "me")
println(tuple._1)
println(tuple._2)
println(tuple._3)
println(tuple._4)
println(tuple._5)
println(tuple._6)
